<?php

namespace BPL\Mods\Terms;

function main(): string
{
    return <<<HTML
    <!-- Terms and Conditions Modal -->
    <div class="modal fade" id="termsModal" tabindex="-1" aria-labelledby="termsModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg">
            <div class="modal-content">
                <!-- Modal Header -->
                <div class="modal-header bg-primary text-white">
                <h5 class="modal-title">Terms and Conditions</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <!-- Modal Body -->
                <div class="modal-body" style="max-height: 70vh; overflow-y: auto;">
                    <h5 class="text-center mb-4">
                        The Software <br>
                        <span class="fs-4">Earnings Disclaimer</span><br>
                        <span class="fs-6">(IMPORTANT - PLEASE READ)</span>
                    </h5>
                    
                    <p><strong>EVERY EFFORT HAS BEEN MADE TO ACCURATELY REPRESENT THIS PRODUCT AND ITS POTENTIAL.</strong> EVEN THOUGH THIS INDUSTRY IS ONE OF THE FEW WHERE ONE CAN WRITE THEIR OWN CHECK IN TERMS OF EARNINGS, THERE IS NO GUARANTEE THAT YOU WILL EARN ANY MONEY USING THE TECHNIQUES AND IDEAS IN THESE MATERIALS. EXAMPLES IN THESE MATERIALS ARE NOT TO BE INTERPRETED AS A PROMISE OR GUARANTEE OF EARNINGS. EARNING POTENTIAL IS ENTIRELY DEPENDENT ON THE PERSON USING OUR PRODUCT, IDEAS, AND TECHNIQUES. WE DO NOT PURPORT THIS AS A "GET RICH SCHEME." ANY CLAIMS MADE OF ACTUAL EARNINGS OR EXAMPLES OF ACTUAL RESULTS CAN BE VERIFIED UPON REQUEST. YOUR LEVEL OF SUCCESS IN ATTAINING THE RESULTS CLAIMED IN OUR MATERIALS DEPENDS ON THE TIME YOU DEVOTE TO THE PROGRAM, IDEAS, AND TECHNIQUES MENTIONED, YOUR FINANCES, KNOWLEDGE, AND VARIOUS SKILLS. SINCE THESE FACTORS DIFFER ACCORDING TO INDIVIDUALS, WE CANNOT GUARANTEE YOUR SUCCESS OR INCOME LEVEL. NOR ARE WE RESPONSIBLE FOR ANY OF YOUR ACTIONS.</p>

                    <p><strong>FORWARD-LOOKING STATEMENTS:</strong> MATERIALS IN OUR PRODUCT AND OUR WEBSITE MAY CONTAIN INFORMATION THAT INCLUDES OR IS BASED UPON FORWARD-LOOKING STATEMENTS WITHIN THE MEANING OF THE SECURITIES LITIGATION REFORM ACT OF 1995. FORWARD-LOOKING STATEMENTS GIVE OUR EXPECTATIONS OR FORECASTS OF FUTURE EVENTS. YOU CAN IDENTIFY THESE STATEMENTS BY THE FACT THAT THEY DO NOT RELATE STRICTLY TO HISTORICAL OR CURRENT FACTS. THEY USE WORDS SUCH AS "ANTICIPATE," "ESTIMATE," "EXPECT," "PROJECT," "INTEND," "PLAN," "BELIEVE," AND OTHER WORDS AND TERMS OF SIMILAR MEANING IN CONNECTION WITH A DESCRIPTION OF POTENTIAL EARNINGS OR FINANCIAL PERFORMANCE.</p>

                    <p><strong>NO GUARANTEES:</strong> ANY AND ALL FORWARD-LOOKING STATEMENTS HERE OR ON ANY OF OUR SALES MATERIAL ARE INTENDED TO EXPRESS OUR OPINION OF EARNINGS POTENTIAL. MANY FACTORS WILL BE IMPORTANT IN DETERMINING YOUR ACTUAL RESULTS, AND NO GUARANTEES ARE MADE THAT YOU WILL ACHIEVE RESULTS SIMILAR TO OURS OR ANYBODY ELSE'S. IN FACT, NO GUARANTEES ARE MADE THAT YOU WILL ACHIEVE ANY RESULTS FROM OUR IDEAS AND TECHNIQUES IN OUR MATERIAL.</p>

                    <p><strong>DISCLAIMER:</strong> THE AUTHOR AND PUBLISHER DISCLAIM ANY WARRANTIES (EXPRESS OR IMPLIED), MERCHANTABILITY, OR FITNESS FOR ANY PARTICULAR PURPOSE. THE AUTHOR AND PUBLISHER SHALL IN NO EVENT BE HELD LIABLE TO ANY PARTY FOR ANY DIRECT, INDIRECT, PUNITIVE, SPECIAL, INCIDENTAL, OR OTHER CONSEQUENTIAL DAMAGES ARISING DIRECTLY OR INDIRECTLY FROM ANY USE OF THIS MATERIAL, WHICH IS PROVIDED "AS IS," AND WITHOUT WARRANTIES.</p>

                    <p><strong>PROFESSIONAL ADVICE:</strong> AS ALWAYS, THE ADVICE OF A COMPETENT LEGAL, TAX, ACCOUNTING, OR OTHER PROFESSIONAL SHOULD BE SOUGHT. THE AUTHOR AND PUBLISHER DO NOT WARRANT THE PERFORMANCE, EFFECTIVENESS, OR APPLICABILITY OF ANY SITES LISTED OR LINKED TO IN THIS SOFTWARE.</p>

                    <p><strong>PRIVACY:</strong> WE MAINTAIN THIS PAGE TO DEMONSTRATE OUR FIRM COMMITMENT TO THE RIGHTS AND PRIVACY OF OUR USERS. THIS PAGE EXPLAINS HOW OUR SITE COLLECTS INFORMATION FROM OUR MEMBERS.</p>

                    <p><strong>NEWSLETTER:</strong> WE RESPECT THE PRIVACY OF OUR USERS, AND AS SUCH, WE WILL NEVER SHARE OUR DATABASE OF EMAIL ADDRESSES AND NAMES WITH ANY THIRD PARTY. UPON CONFIRMATION THAT YOU WOULD LIKE TO JOIN OUR NEWSLETTER, WE WILL FROM TIME TO TIME SEND YOU FREE INFORMATION RELATING TO THE PRODUCTS WE MARKET, GENERAL ADVICE RELATED TO ONLINE MARKETING, AND PROMOTIONAL MATERIAL FOR OTHER PRODUCTS. YOUR EMAIL WILL NEVER BE PASSED ONTO ANY THIRD PARTY. WE WILL ALSO NEVER SPAM YOU. YOU MAY UNSUBSCRIBE FROM THE MAILING LIST AT ANY TIME.</p>

                    <p><strong>REFUND POLICY:</strong> IF YOU PURCHASE THE SOFTWARE AND YOU DO NOT ENJOY THE FINANCIAL FREEDOM THAT YOU EXPECTED, DO NOT MAKE AS MUCH FROM OUR METHODS AS YOU EXPECTED, OR INDEED FOR ANY REASON, YOU MAY CLAIM A REFUND FOR THE PRODUCT WITHIN 60 DAYS OF PURCHASE. ON A SIDENOTE, WE DO ASK YOU TO PUT THE TECHNIQUES INTO USE BEFORE REQUESTING A REFUND, FOR BOTH OUR BENEFIT; HOWEVER, OUR REFUND POLICY IS UNCONDITIONAL AND THIS IS A SUGGESTION, NOT A REQUIREMENT.</p>

                    <p><strong>REVISIONS TO THIS POLICY:</strong> OUR COMPANY RESERVES THE RIGHT TO REVISE, AMEND, OR MODIFY THIS POLICY, OUR TERMS OF SERVICE AGREEMENT, AND OUR OTHER POLICIES AND AGREEMENTS AT ANY TIME AND IN ANY MANNER, BY UPDATING THIS POSTING.</p>
                </div>

                <!-- Modal Footer -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">I Agree</button>
                </div>
            </div>
        </div>
    </div>
    HTML;
}