<?php

namespace BPL\Mods\Terms;

function main(): string
{
	return <<<HTML
    <div id="modal-1" class="uk-modal" style="z-index: 9999">
        <div class="uk-modal-dialog">
            <button type="button" class="uk-modal-close uk-close"></button>
            <h2 style="text-align: center">The Software <br>
                <span style="font-size: larger">Earnings Disclaimer</span><br>
                <span style="font-size: medium">(IMPORTANT - PLEASE READ)</span>
            </h2>
            <p>EVERY EFFORT HAS BEEN MADE TO ACCURATELY REPRESENT THIS PRODUCT AND IT’S POTENTIAL. EVEN THOUGH THIS INDUSTRY IS ONE OF THE FEW WHERE ONE CAN WRITE THEIR OWN CHECK IN TERMS OF EARNINGS, THERE IS NO GUARANTEE THAT YOU WILL EARN ANY MONEY USING THE TECHNIQUES AND IDEAS IN THESE MATERIALS. EXAMPLES IN THESE MATERIALS ARE NOT TO BE INTERPRETED AS A PROMISE OR GUARANTEE OF EARNINGS. EARNING POTENTIAL IS ENTIRELY DEPENDENT ON THE PERSON USING OUR PRODUCT, IDEAS AND TECHNIQUES. WE DO NOT PURPORT THIS AS A "GET RICH SCHEME." ANY CLAIMS MADE OF ACTUAL EARNINGS OR EXAMPLES OF ACTUAL RESULTS CAN BE VERIFIED UPON REQUEST. YOUR LEVEL OF SUCCESS IN ATTAINING THE RESULTS CLAIMED IN OUR MATERIALS DEPENDS ON THE TIME YOU DEVOTE TO THE PROGRAM, IDEAS AND TECHNIQUES MENTIONED, YOUR FINANCES, KNOWLEDGE AND VARIOUS SKILLS. SINCE THESE FACTORS DIFFER ACCORDING TO INDIVIDUALS, WE CANNOT GUARANTEE YOUR SUCCESS OR INCOME LEVEL. NOR ARE WE RESPONSIBLE FOR ANY OF YOUR ACTIONS.</p>
            <p>MATERIALS IN OUR PRODUCT AND OUR WEBSITE MAY CONTAIN INFORMATION THAT INCLUDES OR IS BASED UPON FORWARD-LOOKING STATEMENTS WITHIN THE MEANING OF THE SECURITIES LITIGATION REFORM ACT OF 1995. FORWARD-LOOKING STATEMENTS GIVE OUR EXPECTATIONS OR FORECASTS OF FUTURE EVENTS. YOU CAN IDENTIFY THESE STATEMENTS BY THE FACT THAT THEY DO NOT RELATE STRICTLY TO HISTORICAL OR CURRENT FACTS. THEY USE WORDS SUCH AS "ANTICIPATE," "ESTIMATE," "EXPECT," "PROJECT," "INTEND," "PLAN," "BELIEVE," AND OTHER WORDS AND TERMS OF SIMILAR MEANING IN CONNECTION WITH A DESCRIPTION OF POTENTIAL EARNINGS OR FINANCIAL PERFORMANCE.</p>
            <p>ANY AND ALL FORWARD LOOKING STATEMENTS HERE OR ON ANY OF OUR SALES MATERIAL ARE INTENDED TO EXPRESS OUR OPINION OF EARNINGS POTENTIAL. MANY FACTORS WILL BE IMPORTANT IN DETERMINING YOUR ACTUAL RESULTS AND NO GUARANTEES ARE MADE THAT YOU WILL ACHIEVE RESULTS SIMILAR TO OURS OR ANYBODY ELSES, IN FACT NO GUARANTEES ARE MADE THAT YOU WILL ACHIEVE ANY RESULTS FROM OUR IDEAS AND TECHNIQUES IN OUR MATERIAL.</p>
            <p>The author and publisher disclaim any warranties (express or implied), merchantability, or fitness for any particular purpose. The author and publisher shall in no event be held liable to any party for any direct, indirect, punitive, special, incidental or other consequential damages arising directly or indirectly from any use of this material, which is provided "as is", and without warranties.</p>
            <p>As always, the advice of a competent legal, tax, accounting or other professional should be sought. The author and publisher do not warrant the performance, effectiveness or applicability of any sites listed or linked to in this The software.</p>
            <p>All links are for information purposes only and are not warranted for content, accuracy or any other implied or explicit purpose.</p>
            <h3>Privacy</h3>
            <p>We maintain this page to demonstrate our firm commitment to the rights and privacy of our users. This page explains how our site collects information from our members.</p>
            <p>Free Newsletter and mailing list: we respect the privacy of our users, and as such we will never share our database of email addresses and names with any third party.</p>
            <p>Upon confirmation that you would like to join our newsletter, we will from time to time send you free information relating to the products we market, general advice related to online marketing, and promotional material for other products. Your email will never be passed onto any third party. We will also never spam you. You may unsubscribe from the mailing list at any time.</p>
            <p>Personal Information we collect and how it is used: Service provider: when you purchase The software, the payment is processed by Clicksure.com, who will collect your name, address, and credit card information so as to verify your order. They may not use the information for any other purpose. Upon ordering, we also collect your name and e-mail address. We use this information to follow-up on you as per the above newsletter section.</p>
            <p>Further Reminder - Earnings Disclaimer: Every effort has been made to accurately represent this product and it's potential. Even though this industry is one of the few where one can write their own check in terms of earnings, there is no guarantee that you will earn any money using the techniques and ideas in these materials.</p>
            <p>Examples in these materials are not to be taken as a promise or guarantee of earnings. Earning potential is entirely dependent on the person using our product, ideas, techniques and the effort put forth. We do not purport this as a "get rich scheme", and nor should you view it as such.</p>
            <p>Any and all forward looking statements here or on any of our sales material are intended to express our opinion of earnings potential. Many factors will be important in determining your actual results and no guarantees are made that you will achieve results similar to ours or anybody else’s, in fact no guarantees are made that you will achieve any results from our ideas and techniques.</p>
            <p>Results vary, and as with any money-making opportunity, you could make more or less. Success in ANY money-making opportunity is a result of hard work, time and a variety of other factors. No express or implied guarantees of income are made by The software.</p>
            <p>Returns and refunds policy: as stated, if you purchase The software, and you do not enjoy the financial freedom that you expected, do not make as much from our methods as you expected, or indeed for any reason, you may claim a refund for the product within 60 days of purchase. On a sidenote we do ask you to put the techniques into use before requesting a refund, for both our benefit: however, our refund policy is unconditional and this is a suggestion, not a requirement. We are aware that some buyers will not achieve their personal goals despite our best efforts to the contrary, and we stand by our refund policy as such. Please forward your receipt number (given to you when you ordered) to us and we will action your refund request as quickly as possible, typically within 24 hours.</p>
            <p>Revisions to This Policy: Our company reserves the right to revise, amend, or modify this policy, our Terms Of Service agreement, and our other policies and agreements at any time and in any manner, by updating this posting.</p>
            <p>Privacy Policy: By clicking on "Continue", you are giving us permission to send you emails about our offers. If you chose not to receive any more emails, you can always opt out at any time at the bottom of each email.</p>
            <p>The Software respects the privacy of every individual who visits our websites. This privacy statement provides notice of the standards and terms under which The Software protects the privacy of information supplied by visitors to sites on the World Wide Web that are owned and operated by The Software, including The Software and The Software. This privacy statement provides notice of our information collection practices and of the ways in which your information may be used. This policy may change from time to time, so please check back periodically to review this information.</p>
            <p>A. Personally-Identifiable Information: The Software typically receives specific data about its website visitors only when such information is provided voluntarily, such as when our visitors request information, purchase or enroll for services, open a customer support inquiry ticket, provide resume information for employment opportunities, or send us e-mail. Of course, some of these activities require that you give us information, such as when you make a purchase, use a credit card to pay for services, submit your resume, or request certain types of information. When you provide personally- identifiable information to The Software through one of our websites, it will be used to fulfill your specific request. In most cases, you will be given the opportunity to select whether you do, or do not, want The Software to use this information for additional purposes. You may also request that The Software not use your information by sending an e-mail to: support@fxrevenge.net, however, The Software reserves the right, in its discretion, to send you bulletins and other important information about your The Software services. Absent any instructions from you, The Software may use information you provide to inform you about additional services and products offered by the The Software family of companies, The Software authorized agents, and other goods and services providers with whom The Software has relationships and whose offerings might be of interest to you. The Software will not, however, sell or trade your personally-identifiable information unless we are authorized or legally required to do so, or in the case of imminent physical harm to the visitor or others. On those The Software sites where you may provide The Software with credit card or other ordering information via the web, The Software protects and secures this information by employing commercially customary web- based security and encryption protocols, examples of which include Secure Socket Layer (SSL) and Secure Electronic Transaction (SET). On those sites where you voluntarily offer any feedback, data, answers, questions, comments, suggestions, ideas or the like, The Software will treat that portion of the information as non-confidential and nonproprietary and, except as otherwise expressed in this privacy statement, The Software assumes no obligation to protect such information from disclosure.</p>
            <p>Examples in these materials are not to be taken as a promise or guarantee of earnings. Earning potential is entirely dependent on the person using our product, ideas, techniques and the effort put forth. We do not purport this as a "get rich scheme", and nor should you view it as such.</p>
            <p>B. Non Personally-Identifiable (Generic) Information: In general, The Software gathers some generic information automatically. Generic information does not reveal the identity of the visitor. It usually includes information about the Internet address assigned to your computer, the number and frequency of visitors, and the The Software sites visited. The Software gathers this information for the limited purpose of determining customer service and website needs. We accomplish this by using certain technologies, including "cookies" (a technology that can be used to provide the visitor with tailored information about The Software services). The Software does not combine information collected in this way with any personally-identifiable information. You can set your browser to notify you when you receive a cookie and you can refuse it.</p>
            <p>C. Your The Software hosted website, server, bulletin boards, forum, Third-Party Sites: Information that you disclose in a public space, including on any bulletin board, chat room, or website The Software may host for you as part of your The Software services, is available to anyone else who visits that space. The Software cannot safeguard any information you disclose in these locations. Additionally, The Software websites contain links to sites that belong to third parties unrelated to The Software. The Software cannot protect any information you may disclose in these sites and recommends that you review the privacy policy statements of those sites you visit.</p>
            <p>D. Exceptions and Limitations: Notwithstanding the foregoing and in compliance with applicable laws, The Software (i) cooperates fully with state, local, and federal officials in any investigation relating to any content (including personal or private electronic communications transmitted to The Software) or purported unlawful activities of any user of the Service, and (ii) takes reasonable measures to protect its proprietary rights. For the limited purposes of accomplishing such cooperation and measures and in compliance with applicable laws, The Software may be required to disclose personally identifiable information. In addition, The Software may elect to monitor the areas of communication of any kind (i) to satisfy any law, regulation, or government request; (ii) if such disclosure is necessary or appropriate to operate The Software; or (iii) to protect the rights or property of The Software or others. In connection with the potential sale or transfer of any of its interest in The Software and The Software and other sites owned by the company, The Software reserves the right to sell or transfer your information (including , but not limited to name, address information, and other information you provided to The Software) to a third party that (i) concentrates its business in communication products or services; (ii) agrees to be The Software's successor in interest with regard to the maintenance and protection of information collected and maintained by The Software; and (iii) agrees to the obligations of this policy statement.</p>
        </div>
    </div>
    HTML;
}